### ISSUE TITLE
Migrating all the files from the BlobTable

### ISSUE THREAD

**Issue by mikeryan776** [WSDOT/wsdot-website#102]
Right now, the file migration from BlobTable has an 'earliest_date' argument to limit the files migrated. Initially this was set to the same as the news_article earliest_date, but it appears we have content types like publications and projects where we want to migrate all content to the beginning of time, which means migrating all the files anyway. Two things we can do about this:

1. Migrate all the files, but have a post-migration task to remove all the orphans. We'd take the performance hit of migrating unnecessary files, but would be confident of removing precisely the unused files. The code to do this would be something like

```php
$query = db_select('file_managed', 'fm')
  ->fields('fm', array('fid'));
$query->leftJoin('file_usage', 'fu', 'fm.fid=fu.fid');
$query->isNull('fu.fid');
$result = $query->execute();
foreach ($result as $row) {
  file_delete($row->fid);
}
``` 

2. Have separate file migrations per content type. Each one would replicate the query conditions of the corresponding content type to only pull relevant files - a common parameterized base class should help alleviate the complexity somewhat, but you'd have to be sure to remember that any changes to the node migration queries will also need to be replicated to the file migration queries. This is more complex (and the more complex queries will make each file migration run more slowly), but avoids migrating unnecessary files.

The main questions are, I think

1. What percentage of BlobTable does need to be migrated? If 90% we go with option 1, if 10% option 2, in between...? I think some judicious querying of the data should give us a ballpark here.

2. How slow is the file migration? Coupled with the data from the BlobTable, we can estimate the migration time cost of approach #2.

**Comment by waynedyck** [comment]
If we are only looking at files in the BlobTable which are referenced from the Resources table then I would assume we are only going to be migrating the files we are using and not any orphans. Is that what you are seeing from data in the tables?

**Comment by mikeryan776** [comment]
I hadn't thought of rows in the BlobTable which are not referenced from NodeResources. But, I'm sure we're not using all the blobs referenced by NodeResources - we're limiting news articles imported at least by date, and there are plenty of templateGUIDs we're not importing that presumably reference some blob resources.

So, some querying - I've found of 94719 distinct ResourceBlobId values in NodeResource, 12777 are being referenced by the six TemplateGUIDs we're currently importing, thus that's the maximum number of blobs we actually need to import (it really would be lower than that because the query doesn't take into account date limits). Thus, I think it is worth it to break out the file migrations to only migrate specifically-referenced blobs.

Except, it just occurred to me - is it possible that some of the content we are migrating might contain embedded references to files that are attached to content we're not migrating?

**Comment by mikeryan776** [comment]
Fwiw, in my partial BlobTable data there are no BlobIds not referenced by NodeResource.

**Comment by waynedyck** [comment]
When you consider how long the database has been running with it never being cleaned out and the fact that every time a file is uploaded or replaced it gets a new ID I'm sure there are lots of files which are being used.

**Comment by mikeryan776** [comment]
```
~/Sites/wsdot-website/docroot$ drush mi file
Processed 4324 (3386 created, 938 updated, 0 failed, 0 ignored) in 265.6 sec (977/min) - done with 'file'
```

Creating files from blobs is so much faster than copying them over the intertubes... So, migrating them all wouldn't be too painful.

Now, while we have this issue open for file migration issues, note that "938 updated" above. We saw this scenario when I was onsite - it happens when there are multiple rows being processed for a given "unique" ID. In this case, there are 3386 unique BlobIds being migrated, but the query is putting 4324 rows through the pipeline. The reason for this is we join on the NodeResource table to get the Name column, which we use to generate the filename to save. We have a DISTINCT on our query, but the problem here is that in some cases we have multiple NodeResource rows with different names. E.g.

```
BlobId  BlobFileExt Name                        NodeId
5952	gif	        _Content	                25106
5952	gif	        SR9NooksackToCherryStProj	40919
5952	gif	        SR9NooksackToCherryStProj	62834
```

For blob 5952, node 25106 knows it as _Content.gif, and nodes 40919 and 62834 know it as SR9NooksackToCherryStProj.gif. What actually happens on the Drupal side is it is saved as _Content_1301.gif (_Content is a very popular Name, and Drupal automatically renames to avoid duplicates) and all three nodes point at that file.

So, what can we do about this? 

1. Create multiple (duplicate-content) physical files for each distinct Name, so each node links to a file of the same name as it has in the past? 
2. Create the one physical file which all referencing nodes point to, with whichever Name we find first (and do this dynamically in prepareRow rather than in the query to avoid the multiple-row issue)?
3. ?

**Comment by waynedyck** [comment]
I remember seeing this as well with the SDO exports. On a page you can have multiple links going to the same resource, however, CMS gives each their own unique id. Frustrating. I would say we go with option 2. Create the first filename (although _Content.gif isn't great) and any subsequent nodes looking for the same BlobId will point to it.

**Comment by waynedyck** [comment]
In content types, like Basic page, there will be a Field type, "File" with a Machine name, "field_file"

I am adding this now to different content types.

**Comment by mikeryan776** [comment]
OK. I think what I'll do is fetch all Names associated with the blob, and pick the first one not named "_Content", unless that's the only one.

I'll handle populating field_file in #95.

**Comment by waynedyck** [comment]
Sounds good.
