### ISSUE TITLE
PDF documents are inserted as icons only

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-website#111]
Using CKEditor when one uploads and inserts a pdf document through the media browser all you get is the document icon. In the source it doesn't even reference the link to the file.

**Comment by bertraj** [comment]
Bummer, you gonna rewrite CK editor? or was it reported to Drupal.org?

**Comment by waynedyck** [comment]
From my initial research it appears to be a known issue. I will need to do a bit more research to see if there is a fix or workaround.

**Comment by waynedyck** [comment]
From what I've been able to research, the "Add media" button in the CKEditor is really only meant to insert images and videos and not documents. The preferred way to insert documents into a content type is to use the "File" field as an attachment. Inlining the documents like we currently do doesn't appear to have an easy solution.

**Comment by waynedyck** [comment]
Will add a "File" field to all content types as a way to upload documents. Users will have the option of choosing whether to display the files in a block or copying the URL and linking to them manually in the body of the page content.

**Comment by waynedyck** [comment]
Adding the CKEditor Link File module now allows content authors to use the existing CKEditor Link button and search for and link to internal documents inline with the content. See b8e7a9f
