### ISSUE TITLE
Update Roadwork Content Type and View to Reflect Option 1

### ISSUE THREAD

**Issue by ikenbeb** [WSDOT/wsdot-website#113]
Title: Ditch and Shoulder Repair
Highway:   SR 272  | Region: Eastern | County:  Whitman | Location:  Milepost 0.2
Description: Traffic Impacts: Today, Thursday May 7, until as late as 4:30 p.m., drivers should expect single-lane traffic directed by flaggers. No wide loads allowed.
Work Schedule: Saturday, May 9, 2015 - 08:00 to Thursday, September 10, 2015 - 16:30

**Comment by bertraj** [comment]
Assigned to Bruce for stylistic purposes.
