### ISSUE TITLE
Put Breadcrumb navigation on News items

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-website#127]
Home > News > YYYY > MMMM  Is this possible?

**Comment by waynedyck** [comment]
Possibly. I have this same issue on other pages. Let me take a look

**Comment by waynedyck** [comment]
[Easy Breadcrumb](https://www.drupal.org/project/easy_breadcrumb) uses the current URL (path alias) and the current page's title to automatically extract the breadcrumb's segments and its respective links.

This might be an option.

**Comment by waynedyck** [comment]
Using [Custom Breadcrumbs](https://www.drupal.org/project/custom_breadcrumbs) to fix other nodes on the site, however, I've not found a way yet to get a custom path to work with it which is what I think we need for it to work for the news.

**Comment by waynedyck** [comment]
Limited breadcrumbs are now in place. For the time being we are just showing, **Home > News**
