### ISSUE TITLE
SocialMedia module not working over https

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-website#178]
Mixed content error on news page because `addthis_widget.js` is loaded over regular http. There is an [open issue](https://www.drupal.org/node/2629010) for this on the [Social Media module](https://www.drupal.org/project/socialmedia) page, however, it's been open for the last five months.

In reviewing the `socialmedia.widgets.inc` module I discovered that all external script references are loaded over http rather than https which may present more of an issue than fixing the one on line 469.

**Comment by muffr** [comment]
Would changing the protocol in those links break the module?
________________________________________

**Comment by waynedyck** [comment]
Not sure. I looked through the module and I think one would need to verify that HTTPS was available for all the links.
The other issue is that we'd be modifying the module which might make upgrading it later problematic, so I'd likely submit a patch to the author though I don't know if they are actively working on the module.

**Comment by muffr** [comment]
Would it be possible/advisable to change the protocol now, then revert to the original module before updating? I imagine if they ever do update they will change the protocol to https.

Ryan Muff<mailto:muffr@wsdot.wa.gov>
WSDOT Web Team
360 705 7712<tel:1-360-705-7712>

**Comment by waynedyck** [comment]
Probably. It's not a huge issue at the moment because we are not switching the site to HTTPS everywhere. When we go live the news items will only be viewed by the public over HTTP.
What we will do is confirm all the links in the module work over HTTPS, make the change and then submit a patch to the module author.

**Comment by waynedyck** [comment]
Looks like someone addressed the [SSL HTTP issue](https://www.drupal.org/node/1949074) with the 7.x-1.0-beta16 release of the [Social Media](https://www.drupal.org/project/socialmedia) module.

I will look at applying the update to this module on Monday.
