### ISSUE TITLE
Highways term reference field on Roadwork content type should be auto-complete.

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-website#34]
* Highways is currently a series of checkboxes.
* Confirm that adding when typing in autocomplete field doesn't add a new term to the taxonomy as well.

**Comment by waynedyck** [comment]
As I've discovered with issue #33 the auto-complete field allows adding non-existing terms to the vocabulary by default.

**Comment by muffr** [comment]
David mentioned a way to lock an autocomplete in to current terms. Do you want me to look into this or switch back to a select? Thanks.

Ryan Muff
Interactive Communications
Washington State Department of Transportation
360.705.7712

**Comment by waynedyck** [comment]
Look into it and see what you can find. I found a couple of options but neither of those were overly appealing solutions.
