### ISSUE TITLE
Waze data feed

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-website#395]
Create a data feed for WAZE:

https://developers.google.com/waze/data-feed/overview

**Comment by loganSims** [comment]
Compiled some notes comparing the Waze feed to our Highway Alerts API.

[Waze feed data requirements](https://developers.google.com/waze/data-feed/incident-information) 

[Our highway alerts API](https://www.wsdot.com/traffic/api/Documentation/class_alert.html)

#### Highway Alert to Waze Feed mapping

**incident** - unique ID at least 3 characters. 
Highway Alert equivalent - AlertID 

**polyline** - Latitude and longitude coordinates that describe the location of the incident. 
Highway Alert equivalent - **NONE**

**street** - Specifies the name of the street on which the incident is occurring. 
Highway Alert equivalent - **NONE**

**type** - Describes the alert. Possible types include: ACCIDENT, CONSTRUCTION, HAZARD, and ROAD_CLOSED. 
Highway Alert equivalent - EventCategory 
Notes: Not an exact match. Would need to set up some kind of mapping between our categories and theirs. 

**starttime/endtime** - yyyy-MM-dd'T'HH:mm:ss+HH:mm 
Highway Alert equivalent - StartTime/EndTime 
Notes: Time format isn’t the same. 

**description** - A description of the incident. The description should be less than 40 
Highway Alert equivalent - HeadlineDescription or ExtendedDescription 
Notes: No character limit for our descriptions. Sometimes we add links to our alerts as well, which may not work with Waze. 

**direction** - If you provide 2 or more points, the direction should include one of these: ONE_DIRECTION or BOTH_DIRECTIONS. 
Highway Alert equivalent - **NONE**

**reference** - Identifies the organization from which the information was sourced. The reference name must be a maximum of either 10 capital letters or 12 lowercase letters. 
Notes: We should be okay to use WSDOT here.

**Comment by loganSims** [comment]
The only field that we don't really provide is the `Polyline`. We could calculate one using the `StartRoadwayLocation.Direction` field. The only problem is that the field doesn't always correspond to an actual compass direction.

**Comment by waynedyck** [comment]
Closing for now.
