### ISSUE TITLE
Graph API for Workplace...

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-website#396]
Investigate using https://developers.facebook.com/docs/workplace/security-compliance to download Facebook Workplace data.

**Comment by loganSims** [comment]
https://developers.facebook.com/docs/workplace/integrations/custom-integrations/reference

> The Graph API lets you programmatically read all contents out of your Workplace instance. You can use this approach to batch extracts of your Users, Groups, Posts, Comments, Files, Photos, Videos, and Chat Conversations.

> This API supports a variety of use cases on an ad hoc or periodic frequency:
> * Archiving / Backing up of your Workplace data
> * Feeding an eDiscovery system upon the start of a legal matter
> * Searching for past usage of keywords

Any content not listed there you think we'd need access to?

To access data form the Graph API we need to [create an app for workplace](https://developers.facebook.com/docs/workplace/integrations/custom-integrations/apps). Only **system admins** can do this.

**Comment by loganSims** [comment]
https://developers.facebook.com/docs/workplace/introduction

> To build integrations for Workplace, you need to use Workplace Premium.

If I understand this correctly, we'd need to make an app to access the Graph API, and an app is a type of custom integration.

**Comment by loganSims** [comment]
The Admin panel would also let us download data, but requires Premium. 

https://www.facebook.com/help/work/1858663031075098?helpref=hc_fnav

**Comment by waynedyck** [comment]
Closing for now.
