### ISSUE TITLE
publish ferry data in machine readable format

### ISSUE THREAD

**Issue by bbodenmiller** [WSDOT/wsdot-website#42]
Would like to see the ferry data provided in something like a GTFS-RT format so that OneBusAway, The Transit App, etc. can start including the realtime ferry data.

Related to https://github.com/SoundTransit/soundtransit-rds/issues/22.

**Comment by waynedyck** [comment]
You would be better served looking at our [Traveler Information API](http://www.wsdot.wa.gov/traffic/api/) as that has most of the relevant content already. It's not in a GTFS format, however, that could be done by a third-party developer.

**Comment by bbodenmiller** [comment]
If a scheduled departure changes is that reflected in `ScheduledDeparture` or does that purely return schedule data and not predicted departure time?

**Comment by waynedyck** [comment]
Pretty sure that is just the published scheduled departure time. You can confirm by sending an email to the [WSF Schedule API Feedback](http://www.wsdot.wa.gov/ferries/api/schedule/documentation/contact.html) address.
