### ISSUE TITLE
Event Content type and View

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-website#43]
Please create an event content type with fields:
Title
Description
Date / Time
Location
Host
?? - Subject Taxonomy, how can we relate related events.  Events like tolling.

View
Display a filtered list by county, region, Day of week
Display on a calendar

**Comment by waynedyck** [comment]
Would an example of this be something like the [King County Special Events](http://www.wsdot.wa.gov/Northwest/King/Construction/SpecialEvents.htm) page?

**Comment by bertraj** [comment]
Yes, but also used to display open house and public meeting information.
