### ISSUE TITLE
Configure Feature slideshow block on home page

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-website#52]
The feature block needs to be setup so it shows an image, teaser text and clicking on the image takes one to the configured URL.

Because we currently use the Feature box to link to varying content types some thought has to go into how we are going to set this up within Drupal.

Do we need a generic "Featured" content type which would contain fields for an image, teaser text and a link? We could then add these content types to a Nodequeue which would populate the FlexSlider.

**Comment by muffr** [comment]
Perhaps a Node Queue view including multiple types with rewritten results in the field settings (replacement patterns)?

**Comment by waynedyck** [comment]
I think we will need a general content type for the slideshow block. Because the existing feature box can link to existing pages on our site as well external ones, I don't believe adding additional fields to our existing content types will work all the time.

Why don't you try and create a new content type called, "WSDOT Slideshow Content Type" and have it contain fields for a title, image, teaser text and a URL link. Then setup a Nodequeue for the FlexBox to pull the content from like we have done with the News and Projects.

While you're at it, take a crack at customizing the FlexBox look and feel so it shows the teaser text and clicking on the image takes you to the URL, etc.
