### ISSUE TITLE
Structurally deficient bridge list

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-website#62]
Create a content type and a view for deficient bridges.

http://www.wsdot.wa.gov/Bridge/Reporting/StructurallyDeficientBridges.htm

**Comment by waynedyck** [comment]
Reviewing this, I'm wondering if we need a content type just for deficient bridges whether it needs to be generalized to include all bridges and perhaps have a boolean field allowing it to be marked as deficient. We also have bridges which are marked as "border" and "moveable."

I see the above URL as more like a view of bridges flagged as being deficient.

A general bridge content type could also include an image of the bridge as well as body text about it which would allow us to generate a pages like the [Border Bridges](http://www.wsdot.wa.gov/Bridge/Reporting/BorderBridges.htm) and the [Moveable Bridges](http://www.wsdot.wa.gov/Bridge/Reporting/MoveableBridges.htm) pages.

Thoughts?

**Comment by muffr** [comment]
I agree completely.

**Comment by waynedyck** [comment]
Closing this out for now since it's almost three years old.
