### ISSUE TITLE
Implement population of attachment field on pages

### ISSUE THREAD

**Issue by mikeryan776** [WSDOT/wsdot-website#95]

**Comment by waynedyck** [comment]
I have initially added the 'field_file' to the Basic page with this commit, https://github.com/WSDOT/wsdot-website/commit/1596e1e811a082fb0296bf62624b934ca50968e3

**Comment by waynedyck** [comment]
Need to add field_images for adding attached images as well.

Need to figure out how to handle the duplicates which will be created when migrating multiple copies of the same file into Drupal.
